<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=1280">
    <title>@yield('title')</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f4f7fa;
            color: #333333;
        }
        .email-wrapper {
            width: 100%;
            background-color: #f4f7fa;
            padding: 30px 10px;
        }
        .email-container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #ffffff;
            border-radius: 12px;
            overflow: hidden;
            box-shadow: 0 4px 15px rgba(0,0,0,0.05);
        }
        .email-header {
            background-color: #ffffff;
            text-align: center;
            padding: 30px 20px 20px;
            border-bottom: 2px solid #f0f0f0;
        }
        .email-header img.main-logo {
            max-width: 180px;
            height: auto;
        }
        .email-body {
            padding: 40px 30px;
            background-color: #ffffff;
            line-height: 1.6;
            font-size: 16px;
        }
        .email-body h2 {
            color: #1a1a1a;
            margin-top: 0;
            margin-bottom: 20px;
            font-size: 22px;
        }
        .email-body p {
            margin-bottom: 20px;
            color: #555555;
        }
        .email-footer {
            background-color: #f8f9fc;
            text-align: center;
            padding: 30px 20px;
            font-size: 13px;
            color: #777777;
            border-top: 1px solid #eeeeee;
        }
        .collab-logos {
            margin: 20px 0;
            display: block;
            text-align: center;
        }
        .collab-logos span {
            display: block;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 1px;
            margin-bottom: 10px;
            color: #999999;
        }
        .collab-logos img {
            max-height: 40px;
            vertical-align: middle;
            margin: 0 10px;
        }
        .btn {
            display: inline-block;
            padding: 12px 28px;
            background: linear-gradient(135deg, #00F0FF 0%, #9D4EDD 100%);
            color: #ffffff !important;
            text-decoration: none;
            border-radius: 8px;
            font-weight: bold;
            text-align: center;
            box-shadow: 0 4px 10px rgba(157, 78, 221, 0.3);
            margin: 10px 0;
        }
        .footer-text {
            margin-bottom: 5px;
        }
    </style>
</head>
<body>
    <div class="email-wrapper">
        <div class="email-container">
            
            <!-- HEADER: MORPHO.ID LOGO -->
            <div class="email-header">
                <img src="https://rghwatxwpjdrwcktsxbo.supabase.co/storage/v1/object/public/natey/MorphoID%20Logo.png" alt="Morpho.ID Logo" class="main-logo">
            </div>

            <!-- BODY CONTENT -->
            <div class="email-body">
                @yield('content')
                
                <p style="margin-top: 40px; margin-bottom: 0;">
                    Best Regards,<br>
                    <strong>Morpho.ID System Administrator</strong>
                </p>
            </div>

            <!-- FOOTER: COLLAB LOGOS & INFO -->
            <div class="email-footer">
                <div class="collab-logos">
                    <span>In Collaboration With</span>
                    <img src="https://rghwatxwpjdrwcktsxbo.supabase.co/storage/v1/object/public/natey/FSM%20Logo.png" alt="FSM Logo">
                    <img src="https://rghwatxwpjdrwcktsxbo.supabase.co/storage/v1/object/public/natey/Meta%20logo.png" alt="Meta Logo">
                </div>
                
                <p class="footer-text">This is an automated message generated by the Morpho.ID System.</p>
                <p class="footer-text">Faculty of Science and Mathematics, Universiti Pendidikan Sultan Idris</p>
                <p class="footer-text" style="margin-top: 15px; font-size: 11px;">
                    &copy; {{ date('Y') }} Morpho.ID. All rights reserved.
                </p>
            </div>
            
        </div>
    </div>
</body>
</html>
